name: C/C++ Linux Client

on:
  workflow_dispatch:
  #push:
    #branches: [ master ]
  #pull_request:
    #branches: [ master ]

jobs:
  build-linux:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        
    - name: Install dependencies
        sudo su -c "echo 'deb http://dk.archive.ubuntu.com/ubuntu/ xenial main' >> /etc/apt/sources.list"
        sudo su -c "echo 'deb http://dk.archive.ubuntu.com/ubuntu/ xenial universe' >> /etc/apt/sources.list"
        sudo apt update -y
        sudo apt-get install make
        sudo apt install g++-4.8 gcc-4.8 -y
        sudo apt-get install gcc-4.8-multilib g++-4.8-multilib -y
    - name: Build release
      run: |
        # Note: I set GCC 3.4 as the default compiler because newer versions don't work with some metamod versions
        # cd cl_dll
        # make CC=gcc-3.4
        # cd $GITHUB_WORKSPACE
        cd linux && make hl && make make hl_cdll
        mkdir bugfixedhl-linux
        mkdir -p bugfixedhl-linux/cl_dll
        mkdir -p bugfixedhl-linux/dlls
        cp -i cl_dll/client.so bugfixedhl-linux/cl_dll/client.so
        cp -i dlls/hl.so bugfixedhl-linux/dlls/hl.so
        cp -i network/delta.lst bugfixedhl-linux
        cp -i Readme.txt bugfixedhl-linux
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: bugfixedhl-linux
        path: bugfixedhl-linux/
