name: Windows Release Build

on:
  workflow_dispatch:
  #push:
    #branches: [ master ]
  #pull_request:
    #branches: [ master ]

jobs:

  build-windows-client-release:
    runs-on: windows-2019
  
    steps: 
    - name: Checkout repository
      uses: actions/checkout@v3
      with: 
        fetch-depth: 0
        
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.1.3
        
    - name: Build release
      run: |
        msbuild multiplayer.sln -target:client -p:Configuration=Release
        mkdir hl-windows-client
        mkdir hl-windows-client\client
        copy cl_dll\msvc\Release\client.dll hl-windows-client\client\
        copy cl_dll\msvc\Release\client.pdb hl-windows-client\client\
        copy network\delta.lst hl-windows-client
        copy Readme.txt hl-windows-client
      
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: hl-windows-client-release
        path: hl-windows-client
 
  build-windows-server-release:
    runs-on: windows-2019
  
    steps: 
    - name: Checkout repository
      uses: actions/checkout@v3
      with: 
        fetch-depth: 0
        
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.1.3
        
    - name: Build release
      run: |
        msbuild multiplayer.sln -target:hl -p:Configuration=Release
        mkdir hl-windows-server
        mkdir hl-windows-server\dlls
        copy dlls\msvc\Release\hl.dll hl-windows-server\dlls\
        copy dlls\msvc\Release\hl.pdb hl-windows-server\dlls\
        copy network\delta.lst hl-windows-server
        copy Readme.txt hl-windows-server
      
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: hl-windows-server-release
        path: hl-windows-server
  
